name: starter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  stacked_firebase_auth: ^0.2.1

  cupertino_icons: ^1.0.2
  stacked: ^2.0.2
  stacked_hooks: ^0.2.0
  stacked_services: ^0.8.0-nullsafety.1
  observable_ish: ^3.0.0
  url_launcher: ^6.0.3
  connectivity: ^3.0.3
  device_info: ^2.0.0
  auto_route: ^1.0.2
  google_fonts: ^2.0.0
  path_provider: ^2.0.1
  share: ^2.0.1
  flutter_svg: ^0.20.0-nullsafety.3
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.1
  twitter_login: ^3.0.4
  introduction_screen: ^2.1.0
  intl_phone_number_input: ^0.7.0
  pin_code_fields: ^7.0.0
  google_nav_bar: ^5.0.3
  line_icons: ^2.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator: ^0.3.1-nullsafety.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/google.svg
    - assets/svg/slack.svg
    - assets/i18n/en.json
    - assets/i18n/hi.json
